mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('playground.urls'))
]

mysite/playground/urls.py
from django.urls import path
from . import views

# URLConf
app_name = 'playground'
urlpatterns = [
    path('', views.say_hello, name='hello'),
    path('index', views.IndexView.as_view(), name='index'),
    # path('index2', views.index2, name='index2'),
    # path('index3', views.index3, name='index3'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # path('<int:question_id>/', views.detail, name='detail'),
    # path('<int:question_id>/results/', views.results, name='results'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/playground/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
            return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now >= self.pub_date >= now - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self): 
        return self.choice_text

mysite/playground/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic 
from django.utils import timezone

from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DeleteView):
    model = Question
    template_name = 'detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('playground:results', args=(question.id,)))


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5] 
#     output= ', '.join([q.question_text for q in latest_question_list])
#     return HttpResponse(output)

# def index2(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template('index.html')
#     context = { 'latest_question_list': latest_question_list,}
#     return HttpResponse(template.render(context, request))

# def index3(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'index.html', context)

def say_hello(request):
    return render(request, 'hello.html', { 'name': 'Mosh' })
    
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'detail.html', {'question': question})

    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Quesetion does not exist")
    # return render(request, 'detail.html', {'question': question})


# def results(request, question_id):
#     response = "You're looking at the results of question %s"
#     return HttpResponse(response % question_id)

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'results.html', {'question': question})

mysite/playground/templates/detail.html
<form action="{% url 'playground:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

    <a href="{% url 'playground:index' %}">home</a>

mysite/playground/templates/hello.html
<h1>Yodalehe Yodalehe Yodale he who Yodalehe Yodalehe Yodaloo</h1>
{% if name %}
<h2>Hello {{ name }}</h2>
{% else %}
<h2>Hello World</h2>
{% endif %}

mysite/playground/templates/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'playground/styles.css' %}">

{% if latest_question_list %}
    <h1>Questions</h1>
    {% for question in latest_question_list %}
        <h2><a href="/{{ question.id }}/">{{ question.question_text }}</a></h2>
    {% endfor %}
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/playground/templates/results.html
<h1>{{ question.question_text }}</h1> 
<ul>
    {% for choice in question.choice_set.all %}
    <li> {{ choice.choice_text }}: {{ choice.votes }}</li>
    {% endfor %}
</ul>

<a href="{% url 'playground:detail' question.id %}">Vote again?</a>
<hr>
<a href="{% url 'playground:index' %}">home</a>